# Generated by Django 3.2.25 on 2025-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('Date_Reported_on_first_appointment', models.DateField()),
                ('current_department', models.CharField(max_length=80)),
                ('Department_to', models.CharField(max_length=80)),
                #('Last_date_of_service', models.DateField()),
            ],
        ),
    ]
