# Generated by Django 3.2.25 on 2025-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               # ('Absent2', models.DateField()),
                ('Evidence', models.FileField(upload_to='')),
                ('Specify', models.TextField(max_length=80)),
                #('Resumed', models.DateField()),
                ('specify_here', models.CharField(max_length=80)),
                #('Dateresumed', models.DateField()),
            ],
        ),
    ]
