# Generated by Django 3.2.25 on 2025-02-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_absent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absent',
            new_name='mode',
        ),
    ]
