# Generated by Django 3.2.25 on 2025-02-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_absent_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('Date_Reported_on_first_appointment', models.DateField()),
                ('current_department', models.CharField(max_length=80)),
                ('Department_to', models.CharField(max_length=80)),
                #('Last_date_of_service', models.DateField()),
                #('Absent2', models.DateField()),
                ('Evidence', models.FileField(upload_to='')),
                ('Specify', models.TextField(max_length=80)),
                #('Resumed', models.DateField()),
                ('specify_here', models.CharField(max_length=80)),
                #('Dateresumed', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='mode',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
