# Generated by Django 3.2.25 on 2025-02-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20250204_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Staffmovement',
            name='Absent',
            field=models.DateTimeField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='Staffmovement',
            name='Date_Reported_on_first_appointment',
            field=models.DateTimeField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='Staffmovement',
            name='Dateresumed',
            field=models.DateTimeField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='Staffmovement',
            name='Last_date_of_service',
            field=models.DateTimeField(blank=True,default='', null=True),
        ),
    ]
