# Generated by Django 3.2.25 on 2025-02-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20250204_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmovement',
            name='Absent',
        ),
        migrations.AddField(
            model_name='Staffmovement',
            name='Absent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Date_Reported_on_first_appointment',
            field=models.DateField(blank=True,default='',  null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Dateresumed',
            field=models.DateField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Evidence',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Last_date_of_service',
            field=models.DateField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Resumed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
