# Generated by Django 3.2.25 on 2025-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20250204_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmovement',
            name='Absent',
            field=models.TextField(default='STRING', max_length=80),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Date_Reported_on_first_appointment',
            field=models.DateField(default='',blank=True,null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Last_date_of_service',
            field=models.DateField(default='',blank=True,null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Specify',
            field=models.TextField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='specify_here',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
