# Generated by Django 3.2.25 on 2025-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20250205_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='Absent',
            field=models.DateField(default='',null=True,blank=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Dateresumed',
            field=models.DateField(default='', null=True,blank=True),
        ),
    ]
