# Generated by Django 3.2.25 on 2025-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20250205_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmovement',
            name='Date_Reported_on_first_appointment',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Absent',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Dateresumed',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
