# Generated by Django 3.2.25 on 2025-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_rename_specify_staffmovement_specify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmovement',
            old_name='specify',
            new_name='Specify',
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Absent',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Date_Reported_on_first_appointment',
            field=models.DateField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Absent',
            field=models.DateField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Dateresumed',
            field=models.DateField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Last_date_of_service',
            field=models.DateField(blank=True,default='', null=True),
        ),
    ]
