# Generated by Django 3.2.25 on 2025-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20250205_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Staffmovement',
            name='Date_Reported_on_first_appointment',
            field=models.DateField(blank=True,default='', null=True),
        ),
        migrations.AlterField(
            model_name='Staffmovement',
            name='Absent',
            field=models.DateField(blank=True,default='',null=True),
        ),
        migrations.AlterField(
            model_name='Staffmovement',
            name='Dateresumed',
            field=models.DateField(blank=True, default='',null=True),
        ),
        migrations.AlterField(
            model_name='Staffmovement',
            name='Last_date_of_service',
            field=models.DateField(blank=True,default='', null=True),
        ),
    ]
