# Generated by Django 3.2.25 on 2025-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20250205_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmovement',
            name='Date_Reported_on_first_appointment',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='Dateresumed',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='Department_to',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='Last_date_of_service',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='Resumed',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='Specify',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='Absent',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='current_department',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='specify_here',
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='current',
            field=models.CharField(default='', max_length=30),
        ),
   
        # migrations.AddField(
        #     model_name='staffmovement',
        #     name='date_chosen',
        #     field=models.DateField(null=True,blank=True ,default=''),
        # ),
        # migrations.AddField(
        #     model_name='staffmovement',
        #     name='date_reported',
        #     field=models.DateField(null=True,blank=True,default=''),
        # ),
        # migrations.AddField(
        #     model_name='staffmovement',
        #     name='last_date',
        #     field=models.DateField(null=True,blank=True,default=''),
        # ),
        
        migrations.AddField(
            model_name='staffmovement',
            name='resumed',
            field=models.TextField(default=''),
        ),
      
        # migrations.AddField(
        #     model_name='staffmovement',
        #     name='returned',
        #     field=models.DateField(null=True,blank=True,default=''),
        # ),
        migrations.AddField(
            model_name='staffmovement',
            name='to',
            field=models.CharField(default='', max_length=30),
        ),
        # migrations.AlterField(
        #     model_name='staffmovement',
        #     name='Absent',
        #     field=models.TextField(),
        # ),
        migrations.AlterField(
            model_name='staffmovement',
            name='Evidence',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
