# Generated by Django 3.2.25 on 2025-02-06 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_rename_to_staffmovement_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='Absent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='date_chosen',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 8, 25, 10, 241397, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 8, 25, 10, 241370, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 8, 25, 10, 241397, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 8, 25, 10, 241397, tzinfo=utc)),
        ),
    ]
