# Generated by Django 3.2.25 on 2025-02-06 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20250206_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='Comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='Status',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_chosen',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 55, 14, 502679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 55, 14, 502679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 55, 14, 502679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 9, 55, 14, 502679, tzinfo=utc)),
        ),
    ]
