# Generated by Django 3.2.25 on 2025-02-07 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_auto_20250206_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='Other',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='Others',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_chosen',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 8, 40, 52, 235098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 8, 40, 52, 235098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 8, 40, 52, 235098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 8, 40, 52, 235098, tzinfo=utc)),
        ),
    ]
