# Generated by Django 3.2.25 on 2025-02-11 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20250210_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmovement',
            name='Evidence',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_chosen',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 10, 11, 15, 859150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 10, 11, 15, 859150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 10, 11, 15, 859150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 10, 11, 15, 859150, tzinfo=utc)),
        ),
    ]
