# Generated by Django 3.2.25 on 2025-02-17 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    
    dependencies = [
        ('staff', '0024_auto_20250213_1237'),
    ]

operations = [
    migrations.AlterField(
        model_name='staffmovement',
        name='date_chosen',
        field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 43, 3, 410470, tzinfo=utc)),
    ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 43, 3, 410470, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 43, 3, 410470, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 43, 3, 410470, tzinfo=utc)),
        ),
    ]
