# Generated by Django 3.2.25 on 2025-02-17 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_auto_20250217_1253'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='staffmovement',
            name='date_chosen',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 54, 28, 223294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 54, 28, 223294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 54, 28, 223294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 54, 28, 223294, tzinfo=utc)),
        ),
    ]
