# Generated by Django 3.2.25 on 2025-02-17 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20250217_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmovement',
            name='date_chosen',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 55, 17, 691509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 55, 17, 691509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 55, 17, 691509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='returned',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 55, 17, 691509, tzinfo=utc)),
        ),
    ]
